name: Build and Test Gxsys CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  gxsys-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
